In [ ]:
df = df[(df['날짜_월']==5)|(df['날짜_월']==6)|(df['날짜_월']==7)]
df = df.drop(['날짜','날짜_연도','날짜_월','날짜_일','시간_분','경도','위도','위성천정각','관측고도','계절'], axis = 1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 397440 entries, 261360 to 1248479
Data columns (total 21 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   관측소지점        397440 non-null  int64
 1   자외선지수        397440 non-null  float64
 2   파랑_가시밴드      397440 non-null  float64
 3   초록_가시밴드      397440 non-null  float64
 4   빨강_가시밴드      397440 non-null  float64
 5   식생_가시밴드      397440 non-null  float64
 6   권운_밴드        397440 non-null  float64
 7   눈/얼음_가시밴드    397440 non-null  float64
 8   야간안개/하층운_밴드  397440 non-null  float64
 9   상층_수증기_밴드    397440 non-null  float64
 10  중층_수증기_밴드    397440 non-null  float64
 11  하층_수증기_밴드    397440 non-null  float64
 12  구름상_밴드       397440 non-null  float64
 13  오존_밴드        397440 non-null  float64
 14  대기창_밴드       397440 non-null  float64
 15  깨끗한_대기창_밴드   397440 non-null  float64
 16  오염된_대기창_밴드   397440 non-null  float64
 17  이산화탄소_밴드     397440 non-null  float64
 18  태양천정각        397440 non-null  float64
 19  대기외일사량       397440 non-null  float64
 20  지면타입         397440 non-null  int64
dtypes: float64(19), int64(2)
memory usage: 66.7 MB

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import ARDRegression, BayesianRidge
from sklearn.metrics import r2_score
pd.options.display.max_columns = 30

In [ ]:
df = pd.read_csv('/content/drive/Shareddrives/날씨 빅데이터 분석 경진대회/최종데이터.csv', index_col = 0)

In [ ]:
df = df[(df['날짜_월']==5)|(df['날짜_월']==6)|(df['날짜_월']==7)]
df = df.drop(['날짜','날짜_연도','날짜_월','날짜_일','시간_분','경도','위도','위성천정각','관측고도','계절'], axis = 1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 397440 entries, 261360 to 1248479
Data columns (total 21 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   관측소지점        397440 non-null  int64
 1   자외선지수        397440 non-null  float64
 2   파랑_가시밴드      397440 non-null  float64
 3   초록_가시밴드      397440 non-null  float64
 4   빨강_가시밴드      397440 non-null  float64
 5   식생_가시밴드      397440 non-null  float64
 6   권운_밴드        397440 non-null  float64
 7   눈/얼음_가시밴드    397440 non-null  float64
 8   야간안개/하층운_밴드  397440 non-null  float64
 9   상층_수증기_밴드    397440 non-null  float64
 10  중층_수증기_밴드    397440 non-null  float64
 11  하층_수증기_밴드    397440 non-null  float64
 12  구름상_밴드       397440 non-null  float64
 13  오존_밴드        397440 non-null  float64
 14  대기창_밴드       397440 non-null  float64
 15  깨끗한_대기창_밴드   397440 non-null  float64
 16  오염된_대기창_밴드   397440 non-null  float64
 17  이산화탄소_밴드     397440 non-null  float64
 18  태양천정각        397440 non-null  float64
 19  대기외일사량       397440 non-null  float64
 20  지면타입         397440 non-null  int64
dtypes: float64(19), int64(2)
memory usage: 66.7 MB

In [ ]:
df['Band1'] = df.iloc[:,2:6].mean(axis=1)
df['Band2'] = df.iloc[:,6:8].mean(axis=1)
df['Band3'] = df.iloc[:,8:9].mean(axis=1)
df['Band4'] = df.iloc[:,9:12].mean(axis=1)
df['Band5'] = df.iloc[:,12:18].mean(axis=1)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 397440 entries, 261360 to 1248479
Data columns (total 26 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   관측소지점        397440 non-null  int64
 1   자외선지수        397440 non-null  float64
 2   파랑_가시밴드      397440 non-null  float64
 3   초록_가시밴드      397440 non-null  float64
 4   빨강_가시밴드      397440 non-null  float64
 5   식생_가시밴드      397440 non-null  float64
 6   권운_밴드        397440 non-null  float64
 7   눈/얼음_가시밴드    397440 non-null  float64
 8   야간안개/하층운_밴드  397440 non-null  float64
 9   상층_수증기_밴드    397440 non-null  float64
 10  중층_수증기_밴드    397440 non-null  float64
 11  하층_수증기_밴드    397440 non-null  float64
 12  구름상_밴드       397440 non-null  float64
 13  오존_밴드        397440 non-null  float64
 14  대기창_밴드       397440 non-null  float64
 15  깨끗한_대기창_밴드   397440 non-null  float64
 16  오염된_대기창_밴드   397440 non-null  float64
 17  이산화탄소_밴드     397440 non-null  float64
 18  태양천정각        397440 non-null  float64
 19  대기외일사량       397440 non-null  float64
 20  지면타입         397440 non-null  int64
 21  Band1        397440 non-null  float64
 22  Band2        397440 non-null  float64
 23  Band3        397440 non-null  float64
 24  Band4        397440 non-null  float64
 25  Band5        397440 non-null  float64
dtypes: float64(24), int64(2)
memory usage: 81.9 MB

In [ ]:
df['Band345'] = df.iloc[:,23:26].mean(axis=1)

In [ ]:
bins = list(range(0, 181, 45))
bins_label = list(range(1,6,1))
df["time"] = pd.cut(df['태양천정각'], bins, right=False, labels=bins_label[:-1])

In [ ]:
df = pd.get_dummies(df, columns = ['관측소지점','지면타입','time'])

In [ ]:
pd.options.display.max_columns = 50

In [ ]:
df.columns

Index(['자외선지수', '파랑_가시밴드', '초록_가시밴드', '빨강_가시밴드', '식생_가시밴드', '권운_밴드',
       '눈/얼음_가시밴드', '야간안개/하층운_밴드', '상층_수증기_밴드', '중층_수증기_밴드', '하층_수증기_밴드',
       '구름상_밴드', '오존_밴드', '대기창_밴드', '깨끗한_대기창_밴드', '오염된_대기창_밴드', '이산화탄소_밴드',
       '태양천정각', '대기외일사량', 'Band1', 'Band2', 'Band3', 'Band4', 'Band5',
       'Band345', '관측소지점_13', '관측소지점_105', '관측소지점_108', '관측소지점_112',
       '관측소지점_115', '관측소지점_131', '관측소지점_132', '관측소지점_133', '관측소지점_138',
       '관측소지점_143', '관측소지점_146', '관측소지점_152', '관측소지점_156', '관측소지점_159',
       '관측소지점_165', '지면타입_0', '지면타입_2', '지면타입_3', '지면타입_4', 'time_1', 'time_2',
       'time_3', 'time_4'],
      dtype='object')

In [ ]:
df = df[['자외선지수', '태양천정각', 'Band1', 'Band2','Band345', '관측소지점_13', '관측소지점_105', '관측소지점_108', '관측소지점_112',
       '관측소지점_115', '관측소지점_131', '관측소지점_132', '관측소지점_133', '관측소지점_138',
       '관측소지점_143', '관측소지점_146', '관측소지점_152', '관측소지점_156', '관측소지점_159',
       '관측소지점_165', '지면타입_0', '지면타입_2', '지면타입_3', '지면타입_4', 'time_1', 'time_2','time_3']]

In [ ]:
X  = df.drop(['자외선지수'],axis = 1)
y = df['자외선지수']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state = 50)

In [ ]:
ard_linear, bayesian_ridge = ARDRegression(), BayesianRidge()

In [ ]:
# ard 선형회귀
ard_linear.fit(X_train, y_train)
ard_linear_pred = ard_linear.predict(X_test)
print('ard_linear_RMSE : ', mean_squared_error(ard_linear_pred, y_test, squared = False))
print('ard_linear_r2_score : ', r2_score(y_test,ard_linear_pred))

ard_linear_RMSE :  0.9674663104483187
ard_linear_r2_score :  0.8584643014185924

In [ ]:
from sklearn.metrics import mean_absolute_error

In [ ]:
# 베이지안 릿지 선형회귀
bayesian_ridge.fit(X_train, y_train)
bayesian_ridge_pred = bayesian_ridge.predict(X_test)
print('bayesian_ridge_RMSE : ', mean_squared_error(bayesian_ridge_pred, y_test, squared = False))
print('bayesian_ridge_r2_score : ', r2_score(y_test,bayesian_ridge_pred))

bayesian_ridge_RMSE :  0.9653440076074951
bayesian_ridge_r2_score :  0.8590845858516722

In [ ]:
mean_absolute_error(y_test, bayesian_ridge_pred)

0.7324249511321801

In [ ]:
# 뉴럴 네트워크 회귀(다층 퍼셉트론 회귀)
from sklearn.neural_network import MLPRegressor
mlp = MLPRegressor()

In [ ]:
from sklearn.neural_network import MLPRegressor
mlp = MLPRegressor()

mlp.fit(X_train, y_train)
mlp_pred = mlp.predict(X_test)
print('mlp_regression_RMSE : ', mean_squared_error(mlp_pred, y_test, squared = False))
print('mlp_regression_r2_score : ', r2_score(y_test,mlp_pred))
print('mlp_regression_mae : ', mean_absolute_error(y_test, mlp_pred))

mlp_regression_RMSE :  0.6453633953114912
mlp_regression_r2_score :  0.9370199575685234

In [ ]:
mlp_0 = MLPRegressor(hidden_layer_sizes = (110),random_state=42)

mlp_0.fit(X_train, y_train)
mlp_0_pred = mlp_0.predict(X_test)
print('mlp_0_regression_RMSE : ', mean_squared_error(mlp_0_pred, y_test, squared = False))
print('mlp_0_regression_r2_score : ', r2_score(y_test,mlp_0_pred))
print('mlp_0_regression_mae : ', mean_absolute_error(y_test, mlp_0_pred))

mlp_0_regression_RMSE :  0.6420294919990562
mlp_0_regression_r2_score :  0.9376689780424725
mlp_0_regression_mae :  0.32676365002487257

In [ ]:
mlp_0_1 = MLPRegressor(hidden_layer_sizes = [90],random_state=42)

mlp_0_1.fit(X_train, y_train)
mlp_0_1_pred = mlp_0_1.predict(X_test)
print('mlp_0_1_regression_RMSE : ', mean_squared_error(mlp_0_1_pred, y_test, squared = False))
print('mlp_0_1_regression_r2_score : ', r2_score(y_test,mlp_0_1_pred))
print('mlp_0_1_regression_mae : ', mean_absolute_error(y_test, mlp_0_1_pred))

mlp_0_1_regression_RMSE :  0.6609816610685971
mlp_0_1_regression_r2_score :  0.9339347456116734
mlp_0_1_regression_mae :  0.3315123925515425

In [ ]:
mlp_0_2 = MLPRegressor(hidden_layer_sizes = [80],random_state=42)

mlp_0_2.fit(X_train, y_train)
mlp_0_2_pred = mlp_0_2.predict(X_test)
print('mlp_0_2_regression_RMSE : ', mean_squared_error(mlp_0_2_pred, y_test, squared = False))
print('mlp_0_2_regression_r2_score : ', r2_score(y_test,mlp_0_2_pred))
print('mlp_0_2_regression_mae : ', mean_absolute_error(y_test, mlp_0_2_pred))

mlp_0_2_regression_RMSE :  0.6387541306832002
mlp_0_2_regression_r2_score :  0.9383033285217939
mlp_0_2_regression_mae :  0.3142707489467297

In [ ]:
mlp_1 = MLPRegressor(hidden_layer_sizes=[70, 4], max_iter=5000, alpha=0.005, random_state=42)
mlp_1.fit(X_train, y_train)
mlp_1_pred = mlp_1.predict(X_test)
print('mlp_1_regression_RMSE : ', mean_squared_error(mlp_1_pred, y_test, squared = False))
print('mlp_1_regression_r2_score : ', r2_score(y_test,mlp_1_pred))
print('mlp_1_regression_mae : ', mean_absolute_error(y_test, mlp_1_pred))

mlp_1_regression_RMSE :  0.639906097127433
mlp_1_regression_r2_score :  0.9380805931061225
mlp_1_regression_mae :  0.318758099724335

In [ ]:
mlp_2 = MLPRegressor(hidden_layer_sizes=[80, 4], max_iter=5000, alpha=0.005, random_state=42)
mlp_2.fit(X_train, y_train)
mlp_2_pred = mlp_2.predict(X_test)
print('mlp_2_regression_RMSE : ', mean_squared_error(mlp_2_pred, y_test, squared = False))
print('mlp_2_regression_r2_score : ', r2_score(y_test,mlp_2_pred))
print('mlp_2_regression_mae : ', mean_absolute_error(y_test, mlp_2_pred))

mlp_2_regression_RMSE :  0.6526883366755634
mlp_2_regression_r2_score :  0.9355821841676237
mlp_2_regression_mae :  0.328432127309925

In [ ]:
mlp_3 = MLPRegressor(hidden_layer_sizes=[90, 4], max_iter=5000, alpha=0.005, random_state=42)
mlp_3.fit(X_train, y_train)
mlp_3_pred = mlp_3.predict(X_test)
print('mlp_3_regression_RMSE : ', mean_squared_error(mlp_3_pred, y_test, squared = False))
print('mlp_3_regression_r2_score : ', r2_score(y_test,mlp_3_pred))
print('mlp_3_regression_mae : ', mean_absolute_error(y_test, mlp_3_pred))

mlp_3_regression_RMSE :  0.6399825458925235
mlp_3_regression_r2_score :  0.9380657973572596
mlp_3_regression_mae :  0.32004548385755904

In [ ]:
mlp_4 = MLPRegressor(hidden_layer_sizes=[100, 4], max_iter=5000, alpha=0.005, random_state=42)
mlp_4.fit(X_train, y_train)
mlp_4_pred = mlp_4.predict(X_test)
print('mlp_4_regression_RMSE : ', mean_squared_error(mlp_4_pred, y_test, squared = False))
print('mlp_4_regression_r2_score : ', r2_score(y_test,mlp_4_pred))
print('mlp_4_regression_mae : ', mean_absolute_error(y_test, mlp_4_pred))

mlp_4_regression_RMSE :  0.6470349949113665
mlp_4_regression_r2_score :  0.9366932772591434
mlp_4_regression_mae :  0.3149598050234175

In [ ]:
mlp_5 = MLPRegressor(hidden_layer_sizes=[110, 4], max_iter=5000, alpha=0.005, random_state=42)
mlp_5.fit(X_train, y_train)
mlp_5_pred = mlp_5.predict(X_test)
print('mlp_5_regression_RMSE : ', mean_squared_error(mlp_5_pred, y_test, squared = False))
print('mlp_5_regression_r2_score : ', r2_score(y_test,mlp_5_pred))
print('mlp_5_regression_mae : ', mean_absolute_error(y_test, mlp_5_pred))

mlp_5_regression_RMSE :  0.6465090477676867
mlp_5_regression_r2_score :  0.9367961540983194
mlp_5_regression_mae :  0.3151300899752601

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df_0 = pd.read_csv('/content/drive/Shareddrives/날씨 빅데이터 분석 경진대회/검증/검증데이터_전처리O.csv', index_col = 0)

In [ ]:
df_0.describe()

,관측소지점,자외선지수,태양천정각,지면타입,Band1,Band2,Band3,Band4,Band5,time
count,51855.00000,0.0,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000
mean,127.20000,NaN,72.303571,2.400000,0.139282,0.056884,285.701119,245.476411,268.944311,2.108090
std,35.55162,NaN,35.752869,1.254338,0.188467,0.071855,17.454503,8.656653,16.866734,0.815738
min,13.00000,NaN,9.868750,0.000000,0.000000,0.000000,152.769990,204.743530,206.788640,1.000000
25%,112.00000,NaN,39.776310,2.000000,0.000000,0.000000,276.966935,241.198040,260.638247,1.000000
50%,133.00000,NaN,75.681360,3.000000,0.069990,0.025190,289.077940,247.270977,275.449042,2.000000
75%,152.00000,NaN,106.468055,3.000000,0.192931,0.093765,297.596410,251.072712,280.771033,3.000000
max,165.00000,NaN,124.632510,4.000000,0.966777,0.432200,319.170980,263.843330,298.166843,3.000000

In [ ]:
df_0.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 51855 entries, 0 to 51854
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   관측소지점   51855 non-null  int64
 1   자외선지수   0 non-null      float64
 2   태양천정각   51855 non-null  float64
 3   지면타입    51855 non-null  int64
 4   Band1   51855 non-null  float64
 5   Band2   51855 non-null  float64
 6   Band3   51855 non-null  float64
 7   Band4   51855 non-null  float64
 8   Band5   51855 non-null  float64
 9   time    51855 non-null  int64
dtypes: float64(7), int64(3)
memory usage: 4.4 MB

In [ ]:
df_0['Band345'] = df_0.iloc[:,6:9].mean(axis=1)

In [ ]:
df_0 = pd.get_dummies(df_0, columns = ['관측소지점'])
df_0 = pd.get_dummies(df_0, columns = ['time'])
df_0 = pd.get_dummies(df_0, columns = ['지면타입'])

In [ ]:
df_0.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 51855 entries, 0 to 51854
Data columns (total 30 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   자외선지수      0 non-null      float64
 1   태양천정각      51855 non-null  float64
 2   Band1      51855 non-null  float64
 3   Band2      51855 non-null  float64
 4   Band3      51855 non-null  float64
 5   Band4      51855 non-null  float64
 6   Band5      51855 non-null  float64
 7   Band345    51855 non-null  float64
 8   관측소지점_13   51855 non-null  uint8
 9   관측소지점_105  51855 non-null  uint8
 10  관측소지점_108  51855 non-null  uint8
 11  관측소지점_112  51855 non-null  uint8
 12  관측소지점_115  51855 non-null  uint8
 13  관측소지점_131  51855 non-null  uint8
 14  관측소지점_132  51855 non-null  uint8
 15  관측소지점_133  51855 non-null  uint8
 16  관측소지점_138  51855 non-null  uint8
 17  관측소지점_143  51855 non-null  uint8
 18  관측소지점_146  51855 non-null  uint8
 19  관측소지점_152  51855 non-null  uint8
 20  관측소지점_156  51855 non-null  uint8
 21  관측소지점_159  51855 non-null  uint8
 22  관측소지점_165  51855 non-null  uint8
 23  time_1     51855 non-null  uint8
 24  time_2     51855 non-null  uint8
 25  time_3     51855 non-null  uint8
 26  지면타입_0     51855 non-null  uint8
 27  지면타입_2     51855 non-null  uint8
 28  지면타입_3     51855 non-null  uint8
 29  지면타입_4     51855 non-null  uint8
dtypes: float64(8), uint8(22)
memory usage: 4.6 MB

In [ ]:
df_0.columns

Index(['자외선지수', '태양천정각', 'Band1', 'Band2', 'Band3', 'Band4', 'Band5',
       'Band345', '관측소지점_13', '관측소지점_105', '관측소지점_108', '관측소지점_112',
       '관측소지점_115', '관측소지점_131', '관측소지점_132', '관측소지점_133', '관측소지점_138',
       '관측소지점_143', '관측소지점_146', '관측소지점_152', '관측소지점_156', '관측소지점_159',
       '관측소지점_165', 'time_1', 'time_2', 'time_3', '지면타입_0', '지면타입_2', '지면타입_3',
       '지면타입_4'],
      dtype='object')

In [ ]:
df_0 = df_0[['자외선지수', '태양천정각', 'Band1', 'Band2',
       'Band345', '관측소지점_13', '관측소지점_105', '관측소지점_108', '관측소지점_112',
       '관측소지점_115', '관측소지점_131', '관측소지점_132', '관측소지점_133', '관측소지점_138',
       '관측소지점_143', '관측소지점_146', '관측소지점_152', '관측소지점_156', '관측소지점_159',
       '관측소지점_165', '지면타입_0', '지면타입_2', '지면타입_3',
       '지면타입_4', 'time_1', 'time_2', 'time_3']]

In [ ]:
df_0.describe()

,자외선지수,태양천정각,Band1,Band2,Band345,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,time_1,time_2,time_3
count,0.0,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.00000,51855.000000
mean,NaN,72.303571,0.139282,0.056884,266.707280,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.200000,0.066667,0.666667,0.066667,0.284505,0.32290,0.392595
std,NaN,35.752869,0.188467,0.071855,13.475713,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.400004,0.249446,0.471409,0.249446,0.451183,0.46759,0.488333
min,NaN,9.868750,0.000000,0.000000,189.503767,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
25%,NaN,39.776310,0.000000,0.000000,260.605881,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000
50%,NaN,75.681360,0.069990,0.025190,271.154220,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000
75%,NaN,106.468055,0.192931,0.093765,275.712265,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.00000,1.000000
max,NaN,124.632510,0.966777,0.432200,290.181358,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000

In [ ]:
test = df_0.drop(['자외선지수'], axis=1)
pred = ard_linear.predict(test)
test['자외선지수']=pred

In [ ]:
test.describe()

,태양천정각,Band1,Band2,Band345,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,time_1,time_2,time_3,자외선지수
count,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.00000,51855.000000,51855.000000
mean,72.303571,0.139282,0.056884,266.707280,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.200000,0.066667,0.666667,0.066667,0.284505,0.32290,0.392595,1.795797
std,35.752869,0.188467,0.071855,13.475713,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.400004,0.249446,0.471409,0.249446,0.451183,0.46759,0.488333,2.416947
min,9.868750,0.000000,0.000000,189.503767,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,-3.568827
25%,39.776310,0.000000,0.000000,260.605881,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.082148
50%,75.681360,0.069990,0.025190,271.154220,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000,0.859512
75%,106.468055,0.192931,0.093765,275.712265,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.00000,1.000000,2.809786
max,124.632510,0.966777,0.432200,290.181358,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,8.298212

In [ ]:
test[test['자외선지수']<0]

,태양천정각,Band1,Band2,Band345,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,time_1,time_2,time_3,자외선지수
0,123.72706,0.0,0.0,248.532806,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,-1.115056
1,119.74915,0.0,0.0,255.240625,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,-0.658827
2,119.65871,0.0,0.0,261.731743,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,-0.983657
3,119.71313,0.0,0.0,262.547848,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,-0.579493
4,120.21661,0.0,0.0,249.613523,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,-0.788514
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51850,119.84431,0.0,0.0,271.610746,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,-0.796276
51851,120.42121,0.0,0.0,278.009191,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,-0.672585
51852,120.46896,0.0,0.0,274.867638,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,-0.615452
51853,120.85844,0.0,0.0,271.918007,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,-0.409529
51854,120.72111,0.0,0.0,274.623285,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,-0.803896

In [ ]:
test[(test['자외선지수'] < 0) & (test['태양천정각'] < 90)]

,태양천정각,Band1,Band2,Band345,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,time_1,time_2,time_3,자외선지수
482,89.47500,0.007420,0.001420,270.150939,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.138493
497,87.71068,0.014370,0.004170,270.455523,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.054581
510,88.33519,0.061890,0.049165,236.275001,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.062729
1772,87.74852,0.007987,0.002390,274.875659,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.008526
1787,89.50950,0.003862,0.000645,274.703904,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.112239
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50505,46.24240,0.621803,0.224170,235.866536,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,-1.082094
50515,45.44673,0.564185,0.184615,278.728391,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,-0.722642
51452,86.11385,0.026135,0.007565,272.527797,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.025072
51467,87.87106,0.016137,0.005310,272.443231,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.075334
51482,89.60390,0.005895,0.001290,272.263751,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.134254

In [ ]:
test1 = df_0.drop(['자외선지수'], axis=1)
pred1 = bayesian_ridge.predict(test1)
test1['자외선지수']=pred1

In [ ]:
test1.describe()

,태양천정각,Band1,Band2,Band345,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,time_1,time_2,time_3,자외선지수
count,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.00000,51855.000000,51855.000000
mean,72.303571,0.139282,0.056884,266.707280,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.200000,0.066667,0.666667,0.066667,0.284505,0.32290,0.392595,1.809243
std,35.752869,0.188467,0.071855,13.475713,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.400004,0.249446,0.471409,0.249446,0.451183,0.46759,0.488333,2.413764
min,9.868750,0.000000,0.000000,189.503767,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,-3.524747
25%,39.776310,0.000000,0.000000,260.605881,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.079917
50%,75.681360,0.069990,0.025190,271.154220,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000,0.877409
75%,106.468055,0.192931,0.093765,275.712265,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.00000,1.000000,2.843418
max,124.632510,0.966777,0.432200,290.181358,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,8.315521

In [ ]:
test1[test1['자외선지수']<0]

,태양천정각,Band1,Band2,Band345,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,time_1,time_2,time_3,자외선지수
0,123.72706,0.0,0.0,248.532806,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,-1.154813
1,119.74915,0.0,0.0,255.240625,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,-0.678995
2,119.65871,0.0,0.0,261.731743,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,-0.975838
3,119.71313,0.0,0.0,262.547848,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,-0.566037
4,120.21661,0.0,0.0,249.613523,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,-0.831408
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51850,119.84431,0.0,0.0,271.610746,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,-0.728766
51851,120.42121,0.0,0.0,278.009191,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,-0.564762
51852,120.46896,0.0,0.0,274.867638,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,-0.529308
51853,120.85844,0.0,0.0,271.918007,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,-0.328357
51854,120.72111,0.0,0.0,274.623285,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,-0.717916

In [ ]:
test1[(test1['자외선지수'] < 0) & (test1['태양천정각'] < 90)]

,태양천정각,Band1,Band2,Band345,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,time_1,time_2,time_3,자외선지수
482,89.47500,0.007420,0.001420,270.150939,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.121814
488,88.45187,0.019897,0.008760,232.653259,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.140709
497,87.71068,0.014370,0.004170,270.455523,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.036704
503,86.62994,0.031973,0.019535,233.409066,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.038340
509,89.35821,0.008367,0.002020,239.784127,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,-0.018377
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50503,45.91653,0.516922,0.102150,258.329152,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,-0.400580
50505,46.24240,0.621803,0.224170,235.866536,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,-1.130125
50515,45.44673,0.564185,0.184615,278.728391,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,-0.567883
51467,87.87106,0.016137,0.005310,272.443231,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.045902
51482,89.60390,0.005895,0.001290,272.263751,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.106237

In [ ]:
test2 = df_0.drop(['자외선지수'], axis=1)
pred2 = mlp.predict(test2)
test2['자외선지수']=pred2

In [ ]:
test2.describe()

,태양천정각,Band1,Band2,Band345,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,time_1,time_2,time_3,자외선지수
count,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.000000,51855.00000,51855.000000,51855.000000
mean,72.303571,0.139282,0.056884,266.707280,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.066667,0.200000,0.066667,0.666667,0.066667,0.284505,0.32290,0.392595,1.727092
std,35.752869,0.188467,0.071855,13.475713,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.249446,0.400004,0.249446,0.471409,0.249446,0.451183,0.46759,0.488333,2.494970
min,9.868750,0.000000,0.000000,189.503767,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,-0.867119
25%,39.776310,0.000000,0.000000,260.605881,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.026228
50%,75.681360,0.069990,0.025190,271.154220,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000,0.236718
75%,106.468055,0.192931,0.093765,275.712265,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,1.00000,1.000000,2.718087
max,124.632510,0.966777,0.432200,290.181358,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,10.033115

In [ ]:
test2[test2['자외선지수']<0]

,태양천정각,Band1,Band2,Band345,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,time_1,time_2,time_3,자외선지수
1777,88.58466,0.004492,0.001115,278.371301,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.001230
10121,50.97644,0.768590,0.249420,241.673354,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,-0.782278
10172,56.97711,0.485225,0.139460,246.123094,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.041513
10191,58.55812,0.550495,0.256070,241.721585,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.251369
11434,67.78526,0.316340,0.095975,263.880834,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,-0.052895
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50475,50.41464,0.575845,0.226050,230.832973,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.003045
51443,86.75904,0.009185,0.001265,282.187247,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.001125
51458,88.55179,0.004712,0.000645,281.841991,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.005347
51466,89.13333,0.006755,0.000320,277.075229,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.000291
51472,88.73540,0.005598,0.001420,278.764639,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.001420

In [ ]:
test2[(test2['자외선지수']<0) & (test2['태양천정각'] < 90)]

,태양천정각,Band1,Band2,Band345,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,time_1,time_2,time_3,자외선지수
1777,88.58466,0.004492,0.001115,278.371301,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.001230
10121,50.97644,0.768590,0.249420,241.673354,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0,-0.782278
10172,56.97711,0.485225,0.139460,246.123094,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.041513
10191,58.55812,0.550495,0.256070,241.721585,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.251369
11434,67.78526,0.316340,0.095975,263.880834,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,-0.052895
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50475,50.41464,0.575845,0.226050,230.832973,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.003045
51443,86.75904,0.009185,0.001265,282.187247,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.001125
51458,88.55179,0.004712,0.000645,281.841991,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.005347
51466,89.13333,0.006755,0.000320,277.075229,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.000291
51472,88.73540,0.005598,0.001420,278.764639,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.001420

In [ ]:
test3 = df_0.drop(['자외선지수'], axis=1)
pred3 = mlp_2.predict(test3)
test3['자외선지수']=pred3

In [ ]:
test3[test3['자외선지수']<0]

,태양천정각,Band1,Band2,Band345,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,time_1,time_2,time_3,자외선지수
1958,109.27634,0.0,0.0,276.160167,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,-0.000575
1973,110.58931,0.0,0.0,276.127289,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,-0.001799
1979,109.90469,0.0,0.0,276.244995,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,-0.000079
1988,111.84628,0.0,0.0,276.144201,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,-0.003060
1994,111.25642,0.0,0.0,276.132837,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,-0.001195
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51849,120.05285,0.0,0.0,277.753281,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,-0.010287
51851,120.42121,0.0,0.0,278.009191,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,-0.010190
51852,120.46896,0.0,0.0,274.867638,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,-0.003082
51853,120.85844,0.0,0.0,271.918007,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,-0.000355
51854,120.72111,0.0,0.0,274.623285,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,-0.007667

In [ ]:
test3[(test3['자외선지수']<0) & (test3['태양천정각'] < 90)]

,태양천정각,Band1,Band2,Band345,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,time_1,time_2,time_3,자외선지수
34178,88.88239,0.004655,0.001440,276.525503,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.000113
36346,89.39839,0.003077,0.000945,275.513305,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.002687
39353,89.99728,0.007575,0.002405,275.811363,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.002123
40666,89.29976,0.003625,0.000945,278.096851,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.006941
41506,89.52161,0.009625,0.002730,276.761087,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.005103
42826,89.25720,0.004148,0.001440,278.505614,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.006343
42846,89.80864,0.002795,0.000320,278.681432,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.002773
43666,89.55614,0.009550,0.003200,277.275915,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.006080
43687,89.55208,0.009140,0.003050,279.489105,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.001801
43709,89.22543,0.010845,0.002065,276.079037,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,-0.000609
44986,89.21922,0.003100,0.000000,276.069283,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.003552
44994,89.97353,0.002128,0.000150,280.213754,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,-0.003725
47146,89.18588,0.003310,0.000150,274.985791,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.001517
51466,89.13333,0.006755,0.000320,277.075229,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.005331
51474,89.88377,0.002197,0.000150,280.696538,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,-0.002607

In [ ]:
test4 = df_0.drop(['자외선지수'], axis=1)
pred4 = mlp_1.predict(test4)
test4['자외선지수']=pred4

In [ ]:
test4[test4['자외선지수']<0]

,태양천정각,Band1,Band2,Band345,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,time_1,time_2,time_3,자외선지수
1958,109.27634,0.0,0.0,276.160167,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,-0.000575
1973,110.58931,0.0,0.0,276.127289,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,-0.001799
1979,109.90469,0.0,0.0,276.244995,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,-0.000079
1988,111.84628,0.0,0.0,276.144201,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,-0.003060
1994,111.25642,0.0,0.0,276.132837,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,-0.001195
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51849,120.05285,0.0,0.0,277.753281,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,-0.010287
51851,120.42121,0.0,0.0,278.009191,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,-0.010190
51852,120.46896,0.0,0.0,274.867638,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,-0.003082
51853,120.85844,0.0,0.0,271.918007,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,-0.000355
51854,120.72111,0.0,0.0,274.623285,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,-0.007667

In [ ]:
test4[(test4['자외선지수']<0) & (test4['태양천정각'] < 90)]

,태양천정각,Band1,Band2,Band345,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,time_1,time_2,time_3,자외선지수
34178,88.88239,0.004655,0.001440,276.525503,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.000113
36346,89.39839,0.003077,0.000945,275.513305,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.002687
39353,89.99728,0.007575,0.002405,275.811363,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.002123
40666,89.29976,0.003625,0.000945,278.096851,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.006941
41506,89.52161,0.009625,0.002730,276.761087,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.005103
42826,89.25720,0.004148,0.001440,278.505614,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.006343
42846,89.80864,0.002795,0.000320,278.681432,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.002773
43666,89.55614,0.009550,0.003200,277.275915,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.006080
43687,89.55208,0.009140,0.003050,279.489105,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.001801
43709,89.22543,0.010845,0.002065,276.079037,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,-0.000609
44986,89.21922,0.003100,0.000000,276.069283,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.003552
44994,89.97353,0.002128,0.000150,280.213754,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,-0.003725
47146,89.18588,0.003310,0.000150,274.985791,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.001517
51466,89.13333,0.006755,0.000320,277.075229,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.005331
51474,89.88377,0.002197,0.000150,280.696538,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,-0.002607

In [ ]:
test5 = df_0.drop(['자외선지수'], axis=1)
pred5 = mlp_3.predict(test5)
test5['자외선지수']=pred5

In [ ]:
test5[test5['자외선지수']<0]

,태양천정각,Band1,Band2,Band345,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,time_1,time_2,time_3,자외선지수
0,123.72706,0.0,0.0,248.532806,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,-0.037833
1,119.74915,0.0,0.0,255.240625,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,-0.037081
2,119.65871,0.0,0.0,261.731743,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,-0.035385
3,119.71313,0.0,0.0,262.547848,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,-0.036627
4,120.21661,0.0,0.0,249.613523,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,-0.030669
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51850,119.84431,0.0,0.0,271.610746,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,-0.012081
51851,120.42121,0.0,0.0,278.009191,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,-0.050908
51852,120.46896,0.0,0.0,274.867638,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,-0.044535
51853,120.85844,0.0,0.0,271.918007,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,-0.046683
51854,120.72111,0.0,0.0,274.623285,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,-0.051053

In [ ]:
test5[(test5['자외선지수']<0) & (test5['태양천정각'] < 90)]

,태양천정각,Band1,Band2,Band345,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,time_1,time_2,time_3,자외선지수
466,89.79187,0.006000,0.001115,269.861042,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.048012
469,88.50394,0.010927,0.005810,250.380225,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,-0.019645
481,88.03680,0.010790,0.002045,269.744449,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.028721
482,89.47500,0.007420,0.001420,270.150939,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.034267
483,89.77045,0.006575,0.000645,270.687536,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.036343
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51477,88.95663,0.003788,0.000470,277.494921,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,-0.001263
51479,88.76240,0.006530,0.000320,274.819139,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,-0.025321
51482,89.60390,0.005895,0.001290,272.263751,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.031718
51483,89.41654,0.007450,0.001610,273.255748,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.027818
51486,89.68185,0.005685,0.000965,274.040284,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.040411

In [ ]:
test6 = df_0.drop(['자외선지수'], axis=1)
pred6 = mlp_0_1.predict(test6)
test6['자외선지수']=pred6

In [ ]:
test6[test6['자외선지수']<0]

,태양천정각,Band1,Band2,Band345,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,time_1,time_2,time_3,자외선지수
3,119.71313,0.0,0.0,262.547848,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,-0.008820
6,120.59151,0.0,0.0,257.023362,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,-0.005531
7,120.90345,0.0,0.0,249.517841,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,-0.001866
18,120.04457,0.0,0.0,263.704973,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,-0.009668
21,120.94071,0.0,0.0,258.211462,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,-0.006404
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51845,119.12123,0.0,0.0,270.624077,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,-0.000904
51846,119.03998,0.0,0.0,273.457647,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,-0.015620
51847,119.36566,0.0,0.0,274.831997,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,-0.017673
51851,120.42121,0.0,0.0,278.009191,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,-0.012596
51854,120.72111,0.0,0.0,274.623285,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,-0.000569

In [ ]:
test6[(test6['자외선지수']<0) & (test6['태양천정각'] < 90)]

,태양천정각,Band1,Band2,Band345,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,time_1,time_2,time_3,자외선지수
466,89.79187,0.006000,0.001115,269.861042,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.033635
469,88.50394,0.010927,0.005810,250.380225,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,-0.058085
481,88.03680,0.010790,0.002045,269.744449,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.013735
482,89.47500,0.007420,0.001420,270.150939,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.020252
483,89.77045,0.006575,0.000645,270.687536,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.034108
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51472,88.73540,0.005598,0.001420,278.764639,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.003886
51479,88.76240,0.006530,0.000320,274.819139,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,-0.029253
51482,89.60390,0.005895,0.001290,272.263751,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.021248
51483,89.41654,0.007450,0.001610,273.255748,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.021442
51486,89.68185,0.005685,0.000965,274.040284,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.046936

In [ ]:
test7 = df_0.drop(['자외선지수'], axis=1)
pred7 = mlp_0_2.predict(test7)
test7['자외선지수']=pred7

In [ ]:
test7[test7['자외선지수']<0]

,태양천정각,Band1,Band2,Band345,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,time_1,time_2,time_3,자외선지수
0,123.72706,0.0,0.0,248.532806,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,-0.017752
1,119.74915,0.0,0.0,255.240625,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,-0.018196
2,119.65871,0.0,0.0,261.731743,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,-0.042804
3,119.71313,0.0,0.0,262.547848,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,-0.021949
4,120.21661,0.0,0.0,249.613523,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,-0.018866
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51849,120.05285,0.0,0.0,277.753281,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,-0.028282
51851,120.42121,0.0,0.0,278.009191,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,-0.030317
51852,120.46896,0.0,0.0,274.867638,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,-0.027752
51853,120.85844,0.0,0.0,271.918007,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,-0.026816
51854,120.72111,0.0,0.0,274.623285,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,-0.030036

In [ ]:
test7[(test7['자외선지수']<0) & (test7['태양천정각'] < 90)]

,태양천정각,Band1,Band2,Band345,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,time_1,time_2,time_3,자외선지수
482,89.47500,0.007420,0.001420,270.150939,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.007357
497,87.71068,0.014370,0.004170,270.455523,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.004949
512,85.92352,0.020452,0.005805,270.400850,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.002392
1757,85.96455,0.014205,0.003525,274.971967,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.004816
1772,87.74852,0.007987,0.002390,274.875659,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.007184
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50415,58.71203,0.454622,0.147155,237.501826,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.051432
50460,52.49619,0.568917,0.149615,238.076726,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,-0.150015
51452,86.11385,0.026135,0.007565,272.527797,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.004220
51467,87.87106,0.016137,0.005310,272.443231,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.006345
51482,89.60390,0.005895,0.001290,272.263751,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,-0.008643

In [ ]:
ddff = pd.read_csv('/content/drive/Shareddrives/날씨빅데이터티이임/검증/1-1_검증데이터셋.csv')
ddff ['UV'] = pred
ddff.to_excel(excel_writer='ard_linear.xlsx')

# RMSE :  0.9674663104483187
# r2_score :  0.8584643014185924
# MAE : 0.7347619991416109
# 자외선지수 -값 : 11916   // 주간- : 1329

In [ ]:
dddfff = pd.read_csv('/content/drive/Shareddrives/날씨빅데이터티이임/검증/1-1_검증데이터셋.csv')
dddfff['UV'] = pred1
dddfff.to_excel(excel_writer='bayesian_ridge.xlsx')

# RMSE :  0.9653440076074951
# r2_score :  0.8590845858516722
# MAE : 0.7324249511321801
# 자외선지수 -값 :11870     // 주간- : 1447

In [ ]:
ddddffff = pd.read_csv('/content/drive/Shareddrives/날씨빅데이터티이임/검증/1-1_검증데이터셋.csv')
ddddffff['UV'] = pred2
ddddffff.to_excel(excel_writer='mlp.xlsx')

# RMSE :  0.6453633953114912
# r2_score :  0.9370199575685234
# MAE : 0.3175515544493291
# 자외선지수 -값 : 64    // 주간- : 64

In [ ]:
ddddffff = pd.read_csv('/content/drive/Shareddrives/날씨 빅데이터 분석 경진대회/검증/1-1_검증데이터셋.csv')
ddddffff['UV'] = pred2
ddddffff.to_excel(excel_writer='mlp.xlsx')

# RMSE :  0.6453633953114912
# r2_score :  0.9370199575685234
# MAE : 0.3175515544493291
# 자외선지수 -값 : 64    // 주간- : 64

In [ ]:
abc = pd.read_csv('/content/drive/Shareddrives/날씨 빅데이터 분석 경진대회/검증/1-1_검증데이터셋.csv')
abc['UV'] = pred4
abc.to_csv('mlp_1.csv', index = None)

# RMSE :  0.639906097127433
# r2_score :  0.9380805931061225
# MAE : 0.318758099724335
# 자외선지수 -값 : 2381     // 주간- : 15