In [179]:
import pandas as pd
data = pd.read_csv('C:/Users/pcy07/OneDrive/바탕 화면/2022 날씨공모전/최종데이터.csv')

In [180]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1578960 entries, 0 to 1578959
Data columns (total 32 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Unnamed: 0   1578960 non-null  int64
 1   날짜           1578960 non-null  int64
 2   날짜_연도        1578960 non-null  int64
 3   날짜_월         1578960 non-null  int64
 4   날짜_일         1578960 non-null  int64
 5   시간_분         1578960 non-null  int64
 6   관측소지점        1578960 non-null  int64
 7   경도           1578960 non-null  float64
 8   위도           1578960 non-null  float64
 9   자외선지수        1578960 non-null  float64
 10  파랑_가시밴드      1578960 non-null  float64
 11  초록_가시밴드      1578960 non-null  float64
 12  빨강_가시밴드      1578960 non-null  float64
 13  식생_가시밴드      1578960 non-null  float64
 14  권운_밴드        1578960 non-null  float64
 15  눈/얼음_가시밴드    1578960 non-null  float64
 16  야간안개/하층운_밴드  1578960 non-null  float64
 17  상층_수증기_밴드    1578960 non-null  float64
 18  중층_수증기_밴드    1578960 non-null  float64
 19  하층_수증기_밴드    1578960 non-null  float64
 20  구름상_밴드       1578960 non-null  float64
 21  오존_밴드        1578960 non-null  float64
 22  대기창_밴드       1578960 non-null  float64
 23  깨끗한_대기창_밴드   1578960 non-null  float64
 24  오염된_대기창_밴드   1578960 non-null  float64
 25  이산화탄소_밴드     1578960 non-null  float64
 26  태양천정각        1578960 non-null  float64
 27  위성천정각        1578960 non-null  float64
 28  대기외일사량       1578960 non-null  float64
 29  관측고도         1578960 non-null  float64
 30  지면타입         1578960 non-null  int64
 31  계절           1578960 non-null  int64
dtypes: float64(23), int64(9)
memory usage: 385.5 MB

In [181]:
pd.options.display.max_rows =4000
pd.options.display.max_columns = 30

In [182]:
# 검증데이터가 6월이기 때문에 20,21년의 5,6,7월 데이터만 볼 것
data = data[(data['날짜_월'] == 5) | (data['날짜_월'] == 6) | (data['날짜_월'] == 7)]

In [183]:
data.tail()

,Unnamed: 0,날짜,날짜_연도,날짜_월,날짜_일,시간_분,관측소지점,경도,위도,자외선지수,파랑_가시밴드,초록_가시밴드,빨강_가시밴드,식생_가시밴드,권운_밴드,...,상층_수증기_밴드,중층_수증기_밴드,하층_수증기_밴드,구름상_밴드,오존_밴드,대기창_밴드,깨끗한_대기창_밴드,오염된_대기창_밴드,이산화탄소_밴드,태양천정각,위성천정각,대기외일사량,관측고도,지면타입,계절
1248475,1248475,20210731,2021,7,31,2350,146,127.11900,35.84080,0.1,0.0,0.0,0.0,0.0,0.0,...,236.12825,244.63256,253.42097,289.04391,264.53165,291.90287,290.09587,285.48855,270.82702,124.36364,41.81018,-4.72602,62.90,3,2
1248476,1248476,20210731,2021,7,31,2350,152,129.33472,35.58250,0.0,0.0,0.0,0.0,0.0,0.0,...,235.64237,244.82259,253.63901,285.61006,262.88449,288.27382,286.67481,282.45891,269.23268,125.09137,41.52495,-4.87156,82.00,2,2
1248477,1248477,20210731,2021,7,31,2350,156,126.89158,35.17294,0.0,0.0,0.0,0.0,0.0,0.0,...,236.60649,245.04310,253.49377,285.63638,262.57588,287.50208,284.96722,280.05240,267.56515,124.95628,41.04849,-4.79509,72.38,3,2
1248478,1248478,20210731,2021,7,31,2350,159,129.03203,35.10468,0.0,0.0,0.0,0.0,0.0,0.0,...,236.41609,246.52170,255.96927,284.69604,262.22936,287.43410,286.66069,283.63739,270.60537,125.49764,40.96396,-4.91507,69.56,3,2
1248479,1248479,20210731,2021,7,31,2350,165,126.38121,34.81689,0.0,0.0,0.0,0.0,0.0,0.0,...,236.12825,244.21752,252.21451,277.46217,258.04647,280.29423,277.57615,272.99021,263.16598,125.16440,40.67788,-4.80919,38.00,3,2

In [184]:
data.shape

(397440, 32)

In [185]:
data.describe()

,Unnamed: 0,날짜,날짜_연도,날짜_월,날짜_일,시간_분,관측소지점,경도,위도,자외선지수,파랑_가시밴드,초록_가시밴드,빨강_가시밴드,식생_가시밴드,권운_밴드,...,상층_수증기_밴드,중층_수증기_밴드,하층_수증기_밴드,구름상_밴드,오존_밴드,대기창_밴드,깨끗한_대기창_밴드,오염된_대기창_밴드,이산화탄소_밴드,태양천정각,위성천정각,대기외일사량,관측고도,지면타입,계절
count,3.974400e+05,3.974400e+05,397440.000000,397440.000000,397440.000000,397440.00000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,...,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000
mean,7.549195e+05,2.020562e+07,2020.500000,6.000000,15.836957,1175.00000,127.200000,127.831561,36.104073,1.661867,0.141208,0.137770,0.130861,0.155605,0.020527,...,235.492197,243.462017,250.652251,270.810432,251.451810,272.468884,271.551624,269.181599,258.137812,73.712008,42.114224,1.941658,68.639333,2.400000,1.663043
std,3.983527e+05,5.000688e+03,0.500001,0.820923,8.854238,692.43017,35.551322,1.376364,1.182673,2.575460,0.188678,0.189027,0.191046,0.209781,0.050585,...,6.914859,9.049739,11.159133,19.942096,10.970945,20.984206,21.335293,20.552205,15.289431,35.920106,1.339210,4.919886,46.357474,1.254327,0.472670
min,2.613600e+05,2.020050e+07,2020.000000,5.000000,1.000000,0.00000,13.000000,126.160000,33.300000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,201.146600,199.776710,199.540260,200.510830,215.426620,200.110590,199.663520,199.326390,201.053130,9.868750,38.963590,-6.219740,2.280000,0.000000,1.000000
25%,3.607198e+05,2.020062e+07,2020.000000,5.000000,8.000000,587.50000,112.000000,126.624900,35.172940,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,231.101380,238.123630,244.186950,257.023460,243.816310,257.669470,256.116900,254.119540,247.649590,40.989065,41.048490,-2.998963,47.000000,2.000000,1.000000
50%,7.549195e+05,2.020562e+07,2020.500000,6.000000,16.000000,1175.00000,133.000000,127.372120,36.032590,0.200000,0.073080,0.065580,0.048280,0.061200,0.000600,...,235.740170,244.822590,253.735560,277.683400,254.268690,279.706090,278.935760,276.422650,263.997680,76.824970,42.026080,1.836105,68.940000,3.000000,2.000000
75%,1.149119e+06,2.021062e+07,2021.000000,7.000000,23.250000,1762.50000,152.000000,129.032030,37.477720,2.500000,0.198270,0.190470,0.171060,0.237010,0.011180,...,240.523260,250.071480,258.900270,286.343570,259.886650,288.892290,288.565030,285.858540,270.451690,107.942740,43.670460,6.682820,72.380000,3.000000,2.000000
max,1.248479e+06,2.021073e+07,2021.000000,7.000000,31.000000,2350.00000,165.000000,130.898640,37.751470,13.200000,1.040650,1.041320,1.047530,1.133730,0.584800,...,258.930020,267.558150,272.672930,306.260500,274.654630,310.363620,309.653650,305.173730,280.571430,131.635410,43.954630,9.025490,222.800000,4.000000,2.000000

In [186]:
data.columns

Index(['Unnamed: 0', '날짜', '날짜_연도', '날짜_월', '날짜_일', '시간_분', '관측소지점', '경도',
       '위도', '자외선지수', '파랑_가시밴드', '초록_가시밴드', '빨강_가시밴드', '식생_가시밴드', '권운_밴드',
       '눈/얼음_가시밴드', '야간안개/하층운_밴드', '상층_수증기_밴드', '중층_수증기_밴드', '하층_수증기_밴드',
       '구름상_밴드', '오존_밴드', '대기창_밴드', '깨끗한_대기창_밴드', '오염된_대기창_밴드', '이산화탄소_밴드',
       '태양천정각', '위성천정각', '대기외일사량', '관측고도', '지면타입', '계절'],
      dtype='object')

In [187]:
# 필요한 변수만 선택
data = data[['관측소지점', '자외선지수', '파랑_가시밴드', '초록_가시밴드', '빨강_가시밴드', '식생_가시밴드', '권운_밴드',
       '눈/얼음_가시밴드', '야간안개/하층운_밴드', '상층_수증기_밴드', '중층_수증기_밴드', '하층_수증기_밴드',
       '구름상_밴드', '오존_밴드', '대기창_밴드', '깨끗한_대기창_밴드', '오염된_대기창_밴드', '이산화탄소_밴드',
       '태양천정각','대기외일사량', '지면타입']]

In [188]:
# 채널별 평균으로
data1 = data[['파랑_가시밴드', '초록_가시밴드', '빨강_가시밴드', '식생_가시밴드']]
data['channel1'] = data1.mean(axis=1)

data2 = data[['권운_밴드', '눈/얼음_가시밴드']]
data['channel2'] = data2.mean(axis=1)

data3 = data[['야간안개/하층운_밴드']]
data['channel3'] = data3.mean(axis=1)

data4 = data[[ '상층_수증기_밴드', '중층_수증기_밴드', '하층_수증기_밴드']]
data['channel4'] = data4.mean(axis=1)

data5 = data[[ '구름상_밴드', '오존_밴드', '대기창_밴드', '깨끗한_대기창_밴드', '오염된_대기창_밴드', '이산화탄소_밴드']]
data['channel5'] = data5.mean(axis=1)

In [189]:
data.describe()

,관측소지점,자외선지수,파랑_가시밴드,초록_가시밴드,빨강_가시밴드,식생_가시밴드,권운_밴드,눈/얼음_가시밴드,야간안개/하층운_밴드,상층_수증기_밴드,중층_수증기_밴드,하층_수증기_밴드,구름상_밴드,오존_밴드,대기창_밴드,깨끗한_대기창_밴드,오염된_대기창_밴드,이산화탄소_밴드,태양천정각,대기외일사량,지면타입,channel1,channel2,channel3,channel4,channel5
count,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000
mean,127.200000,1.661867,0.141208,0.137770,0.130861,0.155605,0.020527,0.091856,282.728598,235.492197,243.462017,250.652251,270.810432,251.451810,272.468884,271.551624,269.181599,258.137812,73.712008,1.941658,2.400000,0.141361,0.056191,282.728598,243.202155,265.600360
std,35.551322,2.575460,0.188678,0.189027,0.191046,0.209781,0.050585,0.118946,18.374343,6.914859,9.049739,11.159133,19.942096,10.970945,20.984206,21.335293,20.552205,15.289431,35.920106,4.919886,1.254327,0.194102,0.071775,18.374343,8.918387,18.108959
min,13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,152.769990,201.146600,199.776710,199.540260,200.510830,215.426620,200.110590,199.663520,199.326390,201.053130,9.868750,-6.219740,0.000000,0.000000,0.000000,152.769990,200.154523,202.681847
25%,112.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,271.293640,231.101380,238.123630,244.186950,257.023460,243.816310,257.669470,256.116900,254.119540,247.649590,40.989065,-2.998963,2.000000,0.000000,0.000000,271.293640,237.936300,252.819356
50%,133.000000,0.200000,0.073080,0.065580,0.048280,0.061200,0.000600,0.040630,286.458400,235.740170,244.822590,253.735560,277.683400,254.268690,279.706090,278.935760,276.422650,263.997680,76.824970,1.836105,3.000000,0.063677,0.023350,286.458400,244.854830,271.988409
75%,152.000000,2.500000,0.198270,0.190470,0.171060,0.237010,0.011180,0.153510,295.751060,240.523260,250.071480,258.900270,286.343570,259.886650,288.892290,288.565030,285.858540,270.451690,107.942740,6.682820,3.000000,0.196738,0.093805,295.751060,249.744540,279.960178
max,165.000000,13.200000,1.040650,1.041320,1.047530,1.133730,0.584800,0.695290,320.364760,258.930020,267.558150,272.672930,306.260500,274.654630,310.363620,309.653650,305.173730,280.571430,131.635410,9.025490,4.000000,1.057465,0.442955,320.364760,266.321503,297.536727

In [190]:
data.columns

Index(['관측소지점', '자외선지수', '파랑_가시밴드', '초록_가시밴드', '빨강_가시밴드', '식생_가시밴드', '권운_밴드',
       '눈/얼음_가시밴드', '야간안개/하층운_밴드', '상층_수증기_밴드', '중층_수증기_밴드', '하층_수증기_밴드',
       '구름상_밴드', '오존_밴드', '대기창_밴드', '깨끗한_대기창_밴드', '오염된_대기창_밴드', '이산화탄소_밴드',
       '태양천정각', '대기외일사량', '지면타입', 'channel1', 'channel2', 'channel3',
       'channel4', 'channel5'],
      dtype='object')

In [191]:
data = data[['관측소지점', '자외선지수','channel1', 'channel2', 'channel3', 'channel4','channel5', 
             '태양천정각', '대기외일사량', '지면타입']]
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 397440 entries, 261360 to 1248479
Data columns (total 10 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   관측소지점     397440 non-null  int64
 1   자외선지수     397440 non-null  float64
 2   channel1  397440 non-null  float64
 3   channel2  397440 non-null  float64
 4   channel3  397440 non-null  float64
 5   channel4  397440 non-null  float64
 6   channel5  397440 non-null  float64
 7   태양천정각     397440 non-null  float64
 8   대기외일사량    397440 non-null  float64
 9   지면타입      397440 non-null  int64
dtypes: float64(8), int64(2)
memory usage: 33.4 MB

#### 태양천정각 : 0-45이하 = 1, 45-90이하 = 2, 90-135이하 = 3, 135-180이하 = 4

In [192]:
data.loc[(data['태양천정각']==180)] 
# 각 구간의 경계값 존재 X (이하/미만 상관없을거 같음)

Empty DataFrame
Columns: [관측소지점, 자외선지수, channel1, channel2, channel3, channel4, channel5, 태양천정각, 대기외일사량, 지면타입]
Index: []

In [193]:
bins = list(range(0, 181, 45))
bins

[0, 45, 90, 135, 180]

In [194]:
bins_label = list(range(1,6,1))
bins_label

[1, 2, 3, 4, 5]

In [195]:
data["태양천정각_구분"] = pd.cut(data['태양천정각'], bins, right=False, labels=bins_label[:-1])

In [196]:
# 확인
data.loc[(data['태양천정각_구분']==1)]

,관측소지점,자외선지수,channel1,channel2,channel3,channel4,channel5,태양천정각,대기외일사량,지면타입,태양천정각_구분
262204,115,3.6,0.091220,0.019805,291.18537,247.883007,279.735873,44.04021,6.12842,4,1
262208,138,3.0,0.112462,0.043990,302.65715,253.053693,284.663498,44.78595,6.01863,0,1
262211,152,3.3,0.127522,0.068025,300.56866,253.142497,284.453282,44.70618,6.02422,2,1
262213,159,4.1,0.119860,0.038335,295.63400,254.788577,281.304780,44.83284,6.00327,3,1
262215,13,1.8,0.115888,0.058580,296.59473,249.882317,276.820433,44.71473,5.73836,0,1
...,...,...,...,...,...,...,...,...,...,...,...
1247755,146,3.4,0.110830,0.061575,311.76524,247.708940,287.719825,43.74911,7.53927,3,1
1247757,156,5.1,0.131988,0.066630,312.23529,248.049947,287.069607,43.42949,7.57795,3,1
1247759,165,4.6,0.118312,0.059520,309.17903,248.003330,285.412950,42.96634,7.62347,3,1
1247760,13,0.5,0.309675,0.115585,304.05794,249.080033,281.425048,44.57890,6.43334,0,1
1247774,165,4.1,0.110568,0.056415,308.63454,248.843070,286.636960,44.98817,6.38856,3,1

In [197]:
# 오호 이렇게 하는 방법 !!
#df1_1 = df1[(df1['태양천정각']>=0)&(df1['태양천정각']<=45)]
#df1_1['time'] = 1
#df1_2 = df1[(df1['태양천정각']>45)&(df1['태양천정각']<=90)]
#df1_2['time'] = 2
#df1_3 = df1[(df1['태양천정각']>90)&(df1['태양천정각']<=135)]
#df1_3['time'] = 3
#df1_4 = df1[(df1['태양천정각']>135)&(df1['태양천정각']<=180)]
#df1_4['time'] = 4

#df_f = pd.concat([df1_1,df1_2,df1_3,df1_4])

In [198]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 397440 entries, 261360 to 1248479
Data columns (total 11 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   관측소지점     397440 non-null  int64
 1   자외선지수     397440 non-null  float64
 2   channel1  397440 non-null  float64
 3   channel2  397440 non-null  float64
 4   channel3  397440 non-null  float64
 5   channel4  397440 non-null  float64
 6   channel5  397440 non-null  float64
 7   태양천정각     397440 non-null  float64
 8   대기외일사량    397440 non-null  float64
 9   지면타입      397440 non-null  int64
 10  태양천정각_구분  397440 non-null  category
dtypes: category(1), float64(8), int64(2)
memory usage: 33.7 MB

In [199]:
data = data.drop(['태양천정각'], axis=1)
data.head()

,관측소지점,자외선지수,channel1,channel2,channel3,channel4,channel5,대기외일사량,지면타입,태양천정각_구분
261360,13,0.0,0.0,0.0,277.64337,251.600313,270.337882,-6.11462,0,3
261361,105,0.0,0.0,0.0,287.64354,246.777507,278.406065,-5.60867,3,3
261362,108,0.0,0.0,0.0,277.32743,248.053840,273.667440,-5.59822,3,3
261363,112,0.0,0.0,0.0,278.71774,248.003663,275.266577,-5.60546,3,3
261364,115,0.0,0.0,0.0,281.88250,241.846820,270.326388,-5.66707,4,3

In [200]:
data_dum = pd.get_dummies(data, columns = ['관측소지점', '지면타입', '태양천정각_구분'])
data_dum

,자외선지수,channel1,channel2,channel3,channel4,channel5,대기외일사량,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,태양천정각_구분_1,태양천정각_구분_2,태양천정각_구분_3,태양천정각_구분_4
261360,0.0,0.0,0.0,277.64337,251.600313,270.337882,-6.11462,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
261361,0.0,0.0,0.0,287.64354,246.777507,278.406065,-5.60867,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
261362,0.0,0.0,0.0,277.32743,248.053840,273.667440,-5.59822,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
261363,0.0,0.0,0.0,278.71774,248.003663,275.266577,-5.60546,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
261364,0.0,0.0,0.0,281.88250,241.846820,270.326388,-5.66707,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1248475,0.1,0.0,0.0,296.40523,244.727260,281.981645,-4.72602,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0
1248476,0.0,0.0,0.0,290.86107,244.701323,279.189128,-4.87156,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0
1248477,0.0,0.0,0.0,292.92384,245.047787,278.049852,-4.79509,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0
1248478,0.0,0.0,0.0,286.67795,246.302353,279.210492,-4.91507,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0
1248479,0.0,0.0,0.0,282.79003,244.186760,271.589202,-4.80919,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0

In [201]:
data_dum.reset_index(drop=True,inplace = True)

In [202]:
data_dum

,자외선지수,channel1,channel2,channel3,channel4,channel5,대기외일사량,관측소지점_13,관측소지점_105,관측소지점_108,관측소지점_112,관측소지점_115,관측소지점_131,관측소지점_132,관측소지점_133,관측소지점_138,관측소지점_143,관측소지점_146,관측소지점_152,관측소지점_156,관측소지점_159,관측소지점_165,지면타입_0,지면타입_2,지면타입_3,지면타입_4,태양천정각_구분_1,태양천정각_구분_2,태양천정각_구분_3,태양천정각_구분_4
0,0.0,0.0,0.0,277.64337,251.600313,270.337882,-6.11462,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0
1,0.0,0.0,0.0,287.64354,246.777507,278.406065,-5.60867,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
2,0.0,0.0,0.0,277.32743,248.053840,273.667440,-5.59822,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
3,0.0,0.0,0.0,278.71774,248.003663,275.266577,-5.60546,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
4,0.0,0.0,0.0,281.88250,241.846820,270.326388,-5.66707,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397435,0.1,0.0,0.0,296.40523,244.727260,281.981645,-4.72602,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0
397436,0.0,0.0,0.0,290.86107,244.701323,279.189128,-4.87156,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0
397437,0.0,0.0,0.0,292.92384,245.047787,278.049852,-4.79509,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,1,0
397438,0.0,0.0,0.0,286.67795,246.302353,279.210492,-4.91507,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0
397439,0.0,0.0,0.0,282.79003,244.186760,271.589202,-4.80919,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0

In [203]:
data_dum.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397440 entries, 0 to 397439
Data columns (total 30 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   자외선지수       397440 non-null  float64
 1   channel1    397440 non-null  float64
 2   channel2    397440 non-null  float64
 3   channel3    397440 non-null  float64
 4   channel4    397440 non-null  float64
 5   channel5    397440 non-null  float64
 6   대기외일사량      397440 non-null  float64
 7   관측소지점_13    397440 non-null  uint8
 8   관측소지점_105   397440 non-null  uint8
 9   관측소지점_108   397440 non-null  uint8
 10  관측소지점_112   397440 non-null  uint8
 11  관측소지점_115   397440 non-null  uint8
 12  관측소지점_131   397440 non-null  uint8
 13  관측소지점_132   397440 non-null  uint8
 14  관측소지점_133   397440 non-null  uint8
 15  관측소지점_138   397440 non-null  uint8
 16  관측소지점_143   397440 non-null  uint8
 17  관측소지점_146   397440 non-null  uint8
 18  관측소지점_152   397440 non-null  uint8
 19  관측소지점_156   397440 non-null  uint8
 20  관측소지점_159   397440 non-null  uint8
 21  관측소지점_165   397440 non-null  uint8
 22  지면타입_0      397440 non-null  uint8
 23  지면타입_2      397440 non-null  uint8
 24  지면타입_3      397440 non-null  uint8
 25  지면타입_4      397440 non-null  uint8
 26  태양천정각_구분_1  397440 non-null  uint8
 27  태양천정각_구분_2  397440 non-null  uint8
 28  태양천정각_구분_3  397440 non-null  uint8
 29  태양천정각_구분_4  397440 non-null  uint8
dtypes: float64(7), uint8(23)
memory usage: 29.9 MB

In [204]:
data_dum = data_dum.drop(['태양천정각_구분_4'], axis=1)

####   데이터 전처리 완룡  !!

## 엘라스틱넷

In [205]:
from sklearn.model_selection import train_test_split

X = data_dum.drop(['자외선지수'], axis=1)
y = data_dum['자외선지수']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 99)

In [206]:
from sklearn.linear_model import ElasticNet
import numpy as np

# 엘라스틱넷 적용 선형 회귀 모형 선언
## alpha는 규제의 강도를 의미하며, 높은 숫자일수록 패널티를 크게 부여함
model1 = ElasticNet(alpha = 0.0001, l1_ratio = 0.5)
model2 = ElasticNet(alpha = 0.001, l1_ratio = 0.5)
model3 = ElasticNet(alpha = 0.01, l1_ratio = 0.5)
model4 = ElasticNet(alpha = 0.1, l1_ratio = 0.5)

In [207]:
model1.fit(X_train, y_train)
model2.fit(X_train, y_train)
model3.fit(X_train, y_train)
model4.fit(X_train, y_train)

C:\Users\pcy07\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.240e+03, tolerance: 1.849e+02
  model = cd_fast.enet_coordinate_descent(

ElasticNet(alpha=0.1)

In [208]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

# alpha = 0.0001
y_pred = model1.predict(X_test) # 예측 값
print(mean_squared_error(y_pred, y_test, squared = False))
print(r2_score(y_test,y_pred))

1.0784995143070495
0.8239350051329963

In [209]:
# alpha = 0.001
y_pred = model2.predict(X_test) # 예측 값
print(mean_squared_error(y_pred, y_test, squared = False))
print(r2_score(y_test,y_pred))

1.0861244298813566
0.8214366705011601

In [210]:
# alpha = 0.01
y_pred = model3.predict(X_test) # 예측 값
print(mean_squared_error(y_pred, y_test, squared = False))
print(r2_score(y_test,y_pred))

1.1245134134074137
0.8085909838510057

In [211]:
# alpha = 0.1
y_pred = model4.predict(X_test) # 예측 값
print(mean_squared_error(y_pred, y_test, squared = False))
print(r2_score(y_test,y_pred))

1.3202145585033274
0.7361712342046658

## Best

In [212]:
model = ElasticNet(alpha = 0.0001, l1_ratio = 0.5)
model.fit(X_train, y_train)

C:\Users\pcy07\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.240e+03, tolerance: 1.849e+02
  model = cd_fast.enet_coordinate_descent(

ElasticNet(alpha=0.0001)

In [213]:
y_pred = model.predict(X_test) # 예측 값
print('RMSE : ', mean_squared_error(y_pred, y_test, squared = False))
print('R2_score : ', r2_score(y_test,y_pred))

RMSE :  1.0784995143070495
R2_score :  0.8239350051329963