In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/검증데이터.csv', index_col = 0)

C:\Users\ghaud\anaconda3\lib\site-packages\numpy\lib\arraysetops.py:583: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  mask |= (ar1 == a)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1578960 entries, 0 to 1578959
Data columns (total 31 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   날짜           1578960 non-null  int64
 1   날짜_연도        1578960 non-null  int64
 2   날짜_월         1578960 non-null  int64
 3   날짜_일         1578960 non-null  int64
 4   시간_분         1578960 non-null  int64
 5   관측소지점        1578960 non-null  int64
 6   경도           1578960 non-null  float64
 7   위도           1578960 non-null  float64
 8   자외선지수        1578960 non-null  float64
 9   파랑_가시밴드      1578960 non-null  float64
 10  초록_가시밴드      1578960 non-null  float64
 11  빨강_가시밴드      1578960 non-null  float64
 12  식생_가시밴드      1578960 non-null  float64
 13  권운_밴드        1578960 non-null  float64
 14  눈/얼음_가시밴드    1578960 non-null  float64
 15  야간안개/하층운_밴드  1578960 non-null  float64
 16  상층_수증기_밴드    1578960 non-null  float64
 17  중층_수증기_밴드    1578960 non-null  float64
 18  하층_수증기_밴드    1578960 non-null  float64
 19  구름상_밴드       1578960 non-null  float64
 20  오존_밴드        1578960 non-null  float64
 21  대기창_밴드       1578960 non-null  float64
 22  깨끗한_대기창_밴드   1578960 non-null  float64
 23  오염된_대기창_밴드   1578960 non-null  float64
 24  이산화탄소_밴드     1578960 non-null  float64
 25  태양천정각        1578960 non-null  float64
 26  위성천정각        1578960 non-null  float64
 27  대기외일사량       1578960 non-null  float64
 28  관측고도         1578960 non-null  float64
 29  지면타입         1578960 non-null  int64
 30  계절           1578960 non-null  int64
dtypes: float64(23), int64(8)
memory usage: 385.5 MB

In [ ]:
df1 = df[(df['날짜_월']==5)|(df['날짜_월']==6)|(df['날짜_월']==7)]

In [ ]:
df1 = df1.drop(['날짜','날짜_연도','날짜_월','날짜_일','시간_분','경도','위도','위성천정각','관측고도','계절'], axis=1)
df1.reset_index(drop=True,inplace = True)

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397440 entries, 0 to 397439
Data columns (total 21 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   관측소지점        397440 non-null  int64
 1   자외선지수        397440 non-null  float64
 2   파랑_가시밴드      397440 non-null  float64
 3   초록_가시밴드      397440 non-null  float64
 4   빨강_가시밴드      397440 non-null  float64
 5   식생_가시밴드      397440 non-null  float64
 6   권운_밴드        397440 non-null  float64
 7   눈/얼음_가시밴드    397440 non-null  float64
 8   야간안개/하층운_밴드  397440 non-null  float64
 9   상층_수증기_밴드    397440 non-null  float64
 10  중층_수증기_밴드    397440 non-null  float64
 11  하층_수증기_밴드    397440 non-null  float64
 12  구름상_밴드       397440 non-null  float64
 13  오존_밴드        397440 non-null  float64
 14  대기창_밴드       397440 non-null  float64
 15  깨끗한_대기창_밴드   397440 non-null  float64
 16  오염된_대기창_밴드   397440 non-null  float64
 17  이산화탄소_밴드     397440 non-null  float64
 18  태양천정각        397440 non-null  float64
 19  대기외일사량       397440 non-null  float64
 20  지면타입         397440 non-null  int64
dtypes: float64(19), int64(2)
memory usage: 63.7 MB

In [ ]:
df1.iloc[:,8:9]

        야간안개/하층운_밴드
0         277.64337
1         287.64354
2         277.32743
3         278.71774
4         281.88250
...             ...
397435    296.40523
397436    290.86107
397437    292.92384
397438    286.67795
397439    282.79003

[397440 rows x 1 columns]

In [ ]:
df1['Band1'] = df1.iloc[:,2:6].mean(axis=1)
df1['Band2'] = df1.iloc[:,6:8].mean(axis=1)
df1['Band3'] = df1.iloc[:,8:9].mean(axis=1)
df1['Band4'] = df1.iloc[:,9:12].mean(axis=1)
df1['Band5'] = df1.iloc[:,12:18].mean(axis=1)

In [ ]:
df1.describe()

,관측소지점,자외선지수,파랑_가시밴드,초록_가시밴드,빨강_가시밴드,식생_가시밴드,권운_밴드,눈/얼음_가시밴드,야간안개/하층운_밴드,상층_수증기_밴드,...,오염된_대기창_밴드,이산화탄소_밴드,태양천정각,대기외일사량,지면타입,Band1,Band2,Band3,Band4,Band5
count,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,...,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000,397440.000000
mean,127.200000,1.661867,0.141208,0.137770,0.130861,0.155605,0.020527,0.091856,282.728598,235.492197,...,269.181599,258.137812,73.712008,1.941658,2.400000,0.141361,0.056191,282.728598,243.202155,265.600360
std,35.551322,2.575460,0.188678,0.189027,0.191046,0.209781,0.050585,0.118946,18.374343,6.914859,...,20.552205,15.289431,35.920106,4.919886,1.254327,0.194102,0.071775,18.374343,8.918387,18.108959
min,13.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,152.769990,201.146600,...,199.326390,201.053130,9.868750,-6.219740,0.000000,0.000000,0.000000,152.769990,200.154523,202.681847
25%,112.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,271.293640,231.101380,...,254.119540,247.649590,40.989065,-2.998963,2.000000,0.000000,0.000000,271.293640,237.936300,252.819356
50%,133.000000,0.200000,0.073080,0.065580,0.048280,0.061200,0.000600,0.040630,286.458400,235.740170,...,276.422650,263.997680,76.824970,1.836105,3.000000,0.063677,0.023350,286.458400,244.854830,271.988409
75%,152.000000,2.500000,0.198270,0.190470,0.171060,0.237010,0.011180,0.153510,295.751060,240.523260,...,285.858540,270.451690,107.942740,6.682820,3.000000,0.196738,0.093805,295.751060,249.744540,279.960178
max,165.000000,13.200000,1.040650,1.041320,1.047530,1.133730,0.584800,0.695290,320.364760,258.930020,...,305.173730,280.571430,131.635410,9.025490,4.000000,1.057465,0.442955,320.364760,266.321503,297.536727

In [ ]:
df1['태양천정각'].max()

131.63541

In [ ]:
df1

,관측소지점,자외선지수,파랑_가시밴드,초록_가시밴드,빨강_가시밴드,식생_가시밴드,권운_밴드,눈/얼음_가시밴드,야간안개/하층운_밴드,상층_수증기_밴드,...,오염된_대기창_밴드,이산화탄소_밴드,태양천정각,대기외일사량,지면타입,Band1,Band2,Band3,Band4,Band5
0,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,277.64337,241.10364,...,275.67037,262.71147,130.35092,-6.11462,0,0.0,0.0,277.64337,251.600313,270.337882
1,105,0.0,0.0,0.0,0.0,0.0,0.0,0.0,287.64354,237.44891,...,285.51819,269.40510,126.43187,-5.60867,3,0.0,0.0,287.64354,246.777507,278.406065
2,108,0.0,0.0,0.0,0.0,0.0,0.0,0.0,277.32743,238.35866,...,280.03692,266.81080,126.31564,-5.59822,3,0.0,0.0,277.32743,248.053840,273.667440
3,112,0.0,0.0,0.0,0.0,0.0,0.0,0.0,278.71774,238.44819,...,282.06360,268.05385,126.36437,-5.60546,3,0.0,0.0,278.71774,248.003663,275.266577
4,115,0.0,0.0,0.0,0.0,0.0,0.0,0.0,281.88250,233.40607,...,275.71853,262.56565,126.91833,-5.66707,4,0.0,0.0,281.88250,241.846820,270.326388
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397435,146,0.1,0.0,0.0,0.0,0.0,0.0,0.0,296.40523,236.12825,...,285.48855,270.82702,124.36364,-4.72602,3,0.0,0.0,296.40523,244.727260,281.981645
397436,152,0.0,0.0,0.0,0.0,0.0,0.0,0.0,290.86107,235.64237,...,282.45891,269.23268,125.09137,-4.87156,2,0.0,0.0,290.86107,244.701323,279.189128
397437,156,0.0,0.0,0.0,0.0,0.0,0.0,0.0,292.92384,236.60649,...,280.05240,267.56515,124.95628,-4.79509,3,0.0,0.0,292.92384,245.047787,278.049852
397438,159,0.0,0.0,0.0,0.0,0.0,0.0,0.0,286.67795,236.41609,...,283.63739,270.60537,125.49764,-4.91507,3,0.0,0.0,286.67795,246.302353,279.210492
397439,165,0.0,0.0,0.0,0.0,0.0,0.0,0.0,282.79003,236.12825,...,272.99021,263.16598,125.16440,-4.80919,3,0.0,0.0,282.79003,244.186760,271.589202

In [ ]:
df1_1 = df1[(df1['태양천정각']>=0)&(df1['태양천정각']<=45)]
df1_1['time'] = 1
df1_2 = df1[(df1['태양천정각']>45)&(df1['태양천정각']<=90)]
df1_2['time'] = 2
df1_3 = df1[(df1['태양천정각']>90)&(df1['태양천정각']<=135)]
df1_3['time'] = 3
df1_4 = df1[(df1['태양천정각']>135)&(df1['태양천정각']<=180)]
df1_4['time'] = 4

C:\Users\ghaud\AppData\Local\Temp/ipykernel_26576/390184510.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_1['time'] = 1
C:\Users\ghaud\AppData\Local\Temp/ipykernel_26576/390184510.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_2['time'] = 2
C:\Users\ghaud\AppData\Local\Temp/ipykernel_26576/390184510.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1_3['time'] = 3

In [ ]:
df_2 = pd.concat([df1_1,df1_2,df1_3,df1_4])

In [ ]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 397440 entries, 844 to 397439
Data columns (total 27 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   관측소지점        397440 non-null  int64
 1   자외선지수        397440 non-null  float64
 2   파랑_가시밴드      397440 non-null  float64
 3   초록_가시밴드      397440 non-null  float64
 4   빨강_가시밴드      397440 non-null  float64
 5   식생_가시밴드      397440 non-null  float64
 6   권운_밴드        397440 non-null  float64
 7   눈/얼음_가시밴드    397440 non-null  float64
 8   야간안개/하층운_밴드  397440 non-null  float64
 9   상층_수증기_밴드    397440 non-null  float64
 10  중층_수증기_밴드    397440 non-null  float64
 11  하층_수증기_밴드    397440 non-null  float64
 12  구름상_밴드       397440 non-null  float64
 13  오존_밴드        397440 non-null  float64
 14  대기창_밴드       397440 non-null  float64
 15  깨끗한_대기창_밴드   397440 non-null  float64
 16  오염된_대기창_밴드   397440 non-null  float64
 17  이산화탄소_밴드     397440 non-null  float64
 18  태양천정각        397440 non-null  float64
 19  대기외일사량       397440 non-null  float64
 20  지면타입         397440 non-null  int64
 21  Band1        397440 non-null  float64
 22  Band2        397440 non-null  float64
 23  Band3        397440 non-null  float64
 24  Band4        397440 non-null  float64
 25  Band5        397440 non-null  float64
 26  time         397440 non-null  int64
dtypes: float64(24), int64(3)
memory usage: 84.9 MB

In [ ]:
df_2 = df_2.drop(['대기외일사량','지면타입'],axis=1)

In [ ]:
df_2 = pd.get_dummies(df_2, columns = ['관측소지점','time'])

In [ ]:
from sklearn.preprocessing import MinMaxScaler # 정규화

In [ ]:
df_2['Band345'] = df_2.iloc[:,21:24].mean(axis=1)

In [ ]:
df_2.reset_index(drop=True,inplace = True)

In [ ]:
from sklearn.model_selection import train_test_split

from sklearn.model_selection import cross_val_score, cross_validate,KFold #교차검증

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import RANSACRegressor
from sklearn.linear_model import SGDRegressor

from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from sklearn.metrics import make_scorer

In [ ]:
X = df_2.drop(['Band3','Band4','Band5','자외선지수','파랑_가시밴드','초록_가시밴드','빨강_가시밴드','식생_가시밴드','권운_밴드','눈/얼음_가시밴드',
              '야간안개/하층운_밴드','상층_수증기_밴드','중층_수증기_밴드','하층_수증기_밴드','구름상_밴드','오존_밴드',
              '대기창_밴드','깨끗한_대기창_밴드','오염된_대기창_밴드','이산화탄소_밴드'], axis=1)
y = df_2['자외선지수']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3,random_state=42)

In [ ]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397440 entries, 0 to 397439
Data columns (total 22 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   태양천정각      397440 non-null  float64
 1   Band1      397440 non-null  float64
 2   Band2      397440 non-null  float64
 3   관측소지점_13   397440 non-null  uint8
 4   관측소지점_105  397440 non-null  uint8
 5   관측소지점_108  397440 non-null  uint8
 6   관측소지점_112  397440 non-null  uint8
 7   관측소지점_115  397440 non-null  uint8
 8   관측소지점_131  397440 non-null  uint8
 9   관측소지점_132  397440 non-null  uint8
 10  관측소지점_133  397440 non-null  uint8
 11  관측소지점_138  397440 non-null  uint8
 12  관측소지점_143  397440 non-null  uint8
 13  관측소지점_146  397440 non-null  uint8
 14  관측소지점_152  397440 non-null  uint8
 15  관측소지점_156  397440 non-null  uint8
 16  관측소지점_159  397440 non-null  uint8
 17  관측소지점_165  397440 non-null  uint8
 18  time_1     397440 non-null  uint8
 19  time_2     397440 non-null  uint8
 20  time_3     397440 non-null  uint8
 21  Band345    397440 non-null  float64
dtypes: float64(4), uint8(18)
memory usage: 19.0 MB

# RANSAC Reg

In [1]:
model1 =RANSACRegressor(LinearRegression(),
                        min_samples = 30,#inlier 값 선택 최수 개수
                        max_trials = 80, # 최대 반복 수
                        residual_threshold = 5, # 최대 허용 오차
                        loss = 'absolute_error')
model1.fit(X_train,y_train)

NameError: ignored

In [ ]:
result1 = cross_validate(model1,X_train,y_train, cv=k_fold, scoring=scoring)

In [ ]:
R2 = result1['test_R2 score'].mean()
RMSE = result1['test_RMSE'].mean()

# 훈련 데이터 R2, RMSE
print('훈련 데이터 R2, RMSE')
print('\n')
print('R2_Score : {0: .4f}'.format(R2))
print('RMSE : {0:4f}'.format(RMSE))
print('\n')
y_pred1 = model1.predict(X_test)
print('검증 데이터 R2, RMSE')
print('\n')
print('R2_Score :', r2_score(y_pred1, y_test))
print('RMSE :',mean_squared_error(y_pred1,y_test, squared=False))

In [ ]:
R2 = result1['test_R2 score'].mean()
RMSE = result1['test_RMSE'].mean()

# 훈련 데이터 R2, RMSE
print('훈련 데이터 R2, RMSE')
print('\n')
print('R2_Score : {0: .4f}'.format(R2))
print('RMSE : {0:4f}'.format(RMSE))
print('\n')
y_pred1 = model1.predict(X_test)
print('검증 데이터 R2, RMSE')
print('\n')
print('R2_Score :', r2_score(y_pred1, y_test))
print('RMSE :',mean_squared_error(y_pred1,y_test, squared=False))

In [ ]:
dd = pd.read_csv('검증데이터_전처리O.csv', index_col=0)

In [ ]:
dd = pd.get_dummies(dd, columns=['관측소지점'])

In [ ]:
dd = dd.drop(['대기외일사량'],axis=1)

In [ ]:
dd.info()

In [ ]:
dd['Band345'] = dd.iloc[:,4:7].mean(axis=1)

In [ ]:
test = dd.drop(['Band3','Band4','Band5'],axis=1)

In [ ]:
test = test.drop(['자외선지수'],axis=1)

In [ ]:
pred =model1.predict(test)

In [ ]:
test['자외선지수']=pred

In [ ]:
len(test)

In [ ]:
test[test['자외선지수']<0]

In [ ]:
test.describe()

In [ ]:
test.to_csv('test_날씨.csv')